"""format_report node — renders markdown report and writes to output/."""

from datetime import datetime, timezone
from pathlib import Path

from autosentinel.models import DiagnosticState


def format_report(state: DiagnosticState) -> dict:
    """Format analysis into a markdown report and write to output/."""
    log = state["error_log"]
    analysis = state["analysis_result"]
    source_stem = Path(state["log_path"]).stem
    generated_at = datetime.now(tz=timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")

    confidence_pct = f"{analysis['confidence'] * 100:.0f}%"
    steps = "\n".join(
        f"{i}. {step}" for i, step in enumerate(analysis["remediation_steps"], 1)
    )

    report = f"""# Diagnostic Report: {log['service_name']}

**Generated**: {generated_at}
**Source log**: {state['log_path']}

## Error Summary

- **Service**: {log['service_name']}
- **Error type**: {log['error_type']}
- **Timestamp**: {log['timestamp']}
- **Message**: {log['message']}

## Root Cause Analysis

**Category**: {analysis['error_category']}
**Confidence**: {confidence_pct}

{analysis['root_cause_hypothesis']}

## Remediation Steps

{steps}

---
*Report generated by AutoSentinel Core Diagnostic Engine*
"""

    output_dir = Path("output")
    output_dir.mkdir(parents=True, exist_ok=True)
    report_path = output_dir / f"{source_stem}-report.md"
    report_path.write_text(report, encoding="utf-8")

    return {"report_text": report, "report_path": str(report_path.resolve())}
